plugins {
    id "java"
	id "checkstyle"
	id "org.springframework.boot" version "4.0.6"
    id "io.spring.dependency-management" version "1.1.7"
    id "io.spring.javaformat" version "$javaformatVersion"
    id "org.asciidoctor.jvm.convert" version "4.0.2"
}

group = "io.spring.project-api"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

ext {
	snippetsDir = file("build/generated-snippets")
}

repositories {
	mavenCentral()
}

checkstyle {
	toolVersion = "12.1.2"
}

dependencies {
    checkstyle("io.spring.javaformat:spring-javaformat-checkstyle:${javaformatVersion}")

	implementation("org.springframework.boot:spring-boot-starter-cache")
	implementation("org.springframework.boot:spring-boot-starter-hateoas")
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
	implementation("org.springframework.boot:spring-boot-starter-webmvc")
	implementation("org.springframework.boot:spring-boot-starter-validation")
	implementation("com.azure.spring:spring-cloud-azure-starter-keyvault-secrets")
	implementation("com.vladsch.flexmark:flexmark-all:0.64.8")
	implementation("jakarta.xml.bind:jakarta.xml.bind-api:4.0.5")
	implementation("org.apache.maven:maven-artifact:3.9.16")

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
	testImplementation 'org.springframework.boot:spring-boot-starter-cache-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-hateoas-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-restclient-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-restdocs'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
}

dependencyManagement {
	imports {
		mavenBom "com.azure.spring:spring-cloud-azure-dependencies:7.0.0"
	}
}

tasks.named("test") {
	useJUnitPlatform()
	outputs.dir snippetsDir
}

asciidoctor {
	attributes "snippets": snippetsDir
	dependsOn test
}

bootJar {
	dependsOn asciidoctor
	from("${asciidoctor.outputDir}/index.html") {
		into "static/restdocs"
	}
}
